import dev.qiandeng.chanting.client.StaffAudioGate;
import dev.qiandeng.chanting.StaffAudioSession;
import dev.qiandeng.chanting.client.StaffAudioDrain;
import dev.qiandeng.chanting.client.StaffReleaseGate;

public class StaffAudioGateTest {
    static int n;
    static void check(boolean x, String label) { n++; if (!x) throw new AssertionError(label); }
    public static void main(String[] args) {
        var c = new StaffAudioGate(); long t = 1_000;
        check(c.pendingFlush() == -1 && !c.ready(), "idle has no audio work");
        c.begin(t); long initial = c.pendingFlush();
        check(initial >= 0 && c.takeRequest(t + 200) == null, "first raise requires actual flush and server nonce");
        c.start("g1"); check(c.takeRequest(t + 200) == null, "nonce alone cannot enable PTT");
        c.flushed(initial, 14); var r = c.takeRequest(t + 200);
        check(r.id().equals("g1") && r.revision() == 0 && r.floor() == 14, "send exact native floor");
        check(c.takeRequest(t + 200) == null && !c.ready(), "single send and no premature microphone");
        c.acknowledge("other", 0, 14, true, t + 200); c.acknowledge("g1", 1, 14, true, t + 200); c.acknowledge("g1", 0, 13, true, t + 200);
        check(!c.ready(), "identity/revision/floor must all match");
        c.acknowledge("g1", 0, 14, true, t + 200); check(c.ready(), "matching ACK enables voice");
        c.select(1, t + 20); check(!c.ready() && !c.failed(t + 9_000_000_000L), "shortcut never waits for audio ACK");
        long obsolete = c.pendingFlush(); c.select(0, t + 30);
        c.flushed(obsolete, 15); check(c.takeRequest(t + 200) == null, "ultrafast return cannot consume obsolete audio flush");
        c.flushed(c.pendingFlush(), 16); r = c.takeRequest(t + 200);
        check(r.revision() == 2 && r.floor() == 16, "voice return requests fresh revision/floor");
        c.acknowledge("g1", 0, 14, true, t + 200); check(!c.ready(), "old ACK after return cannot reopen mic");
        c.acknowledge("g1", 2, 16, true, t + 200); check(c.ready(), "new boundary confirmed without 1200ms silence");
        c.end(); c.acknowledge("g1", 2, 16, true, t + 200); check(!c.ready() && c.pendingFlush() == -1, "release ignores ACK");
        c.begin(t + 100); c.start("old-start"); c.flushed(c.pendingFlush(), 20); c.takeRequest(t + 200);
        c.start("new-start"); r = c.takeRequest(t + 200);
        check(r.id().equals("new-start") && !c.ready(), "ordered newest start replaces delayed prior gesture");
        c.acknowledge("old-start", 0, 20, true, t + 200); check(!c.ready(), "replaced nonce ACK ignored");
        c.acknowledge("new-start", 0, 20, false, t + 200); check(c.failed(t + 101), "recorder rejection fails closed");
        c.begin(t); check(!c.failed(t + 1_999_999_999L) && c.failed(t + 2_000_000_000L), "missing audio thread/server ACK has bounded deadline");
        var server = new StaffAudioSession("g1");
        check(server.matches("g1", 0, -1) && !server.ready(), "server initial fence required");
        check(!server.matches("g0", 0, -1) && !server.matches("g1", 1, -1), "server does not borrow other nonce/revision");
        check(!server.matches("g1", 0, -2) && !server.matches("g1", 0, Long.MAX_VALUE), "invalid floor rejected");
        check(server.select(8) && server.revision() == 1 && !server.matches("g1", 1, 10), "shortcut immediate but voice rejected");
        check(server.select(0) && server.matches("g1", 2, 10), "return mode has fresh fence revision");
        server.confirm(); check(server.ready() && !server.matches("g1", 2, 10), "ACK install cannot be replayed");
        check(server.end("release") && !server.end("release") && server.ready(), "release retains claim readiness, emits end once");
        check(!server.select(1) && !server.matches("g1", 2, 11), "late mode/fence frozen after release");
        check(server.end("cancel") && !server.end("cancel") && !server.end("release"), "grace-period GUI cancellation is one-shot");
        var drain = new StaffAudioDrain();
        check(drain.update(1, 960, 320) == StaffAudioDrain.State.PENDING, "partial input queue cannot be read as a full frame");
        check(drain.update(1, 960, 900) == StaffAudioDrain.State.READY, "next normal poll discards old partial PCM; new arrivals cannot prolong drain");
        check(drain.update(2, 960, 2400) == StaffAudioDrain.State.PENDING, "new epoch snapshots its own queue");
        check(drain.update(2, 960, 2000) == StaffAudioDrain.State.PENDING, "multiple old frames drain incrementally");
        check(drain.update(2, 960, 2000) == StaffAudioDrain.State.PENDING, "remaining partial requires one more poll");
        check(drain.update(2, 960, 2000) == StaffAudioDrain.State.READY, "all pre-boundary samples have gone");
        check(drain.update(3, 960, 48001) == StaffAudioDrain.State.FAILED, "excess backlog fails boundedly");
        check(drain.update(4, 0, 0) == StaffAudioDrain.State.FAILED, "no captured frame cannot claim a drain");
        var release = new StaffReleaseGate(); Object staff = new Object();
        check(release.update(staff, 5, true, true, true, 0).began(), "first sampled raise");
        release.update(staff, 6, true, true, true, 1); c.begin(t); c.select(1, t + 1);
        var fastRaise = release.update(staff, 0, true, true, true, 0);
        check(fastRaise.began() && release.mode() == 0, "same stack released and raised between samples is a new gesture");
        if (fastRaise.began()) c.begin(t + 2);
        c.start("new-fast"); c.flushed(c.pendingFlush(), 32); r = c.takeRequest(t + 200);
        check(r.revision() == 0 && r.id().equals("new-fast"), "audio revision and default voice restart with release gate");
        c.acknowledge("new-fast", 0, 32, false, t + 200);
        check(c.failed(t + 3) && c.takeRequest(t + 200) == null, "unavailable voice stops retrying");
        c.acknowledge("new-fast", 0, 32, true, t + 200); check(!c.ready(), "late success cannot revive rejected attempt");
        c.select(1, t + 4); release.update(staff, 1, true, true, true, 1);
        check(!c.failed(t + 9_000_000_000L), "no microphone does not cancel shoulder shortcut mode");
        check(release.update(null, 0, true, false, true, 0).castSlot() == 1, "rejected microphone still permits exactly one selected release");
        check(release.update(null, 0, true, false, true, 0).castSlot() == 0, "no duplicate release");
        c.select(0, t + 5); check(!c.failed(t + 6) && c.pendingFlush() >= 0, "explicit return starts one new bounded attempt");
        c.begin(t); c.start("late"); long lateEpoch = c.pendingFlush();
        c.flushed(lateEpoch, 99);
        check(c.takeRequest(t + 2_000_000_001L) == null, "late flush cannot submit a timed-out epoch");
        c.acknowledge("late", 0, 99, true, t + 2_000_000_002L);
        check(!c.ready(), "late ACK cannot revive timeout before next client tick");
        c.begin(t); c.start("late-ack"); c.flushed(c.pendingFlush(), 100); c.takeRequest(t + 1);
        c.acknowledge("late-ack", 0, 100, true, t + 2_000_000_001L);
        check(!c.ready() && c.failed(t + 2_000_000_002L), "already-sent request's late ACK also expires");
        System.out.println("{\"ok\":true,\"assertions\":" + n + "}");
    }
}
