config-version: 9
debug: false
debug-options: []
enable-metrics: true
language: en-default
save-instantly: true
convert-player-items: false
convert-all-player-items: true
convert-player-items-exceptions: []
ignore-failed-server-assumption-tests: false
bypass-spawn-blocking: true
check-shop-interaction-result: false
enable-world-guard-restrictions: false
require-world-guard-allow-shop-flag: false
register-world-guard-allow-shop-flag: true
enable-towny-restrictions: false
check-spawn-location-interaction-result: false
disable-inventory-verification: false
shop-creation-item:
  type: VILLAGER_SPAWN_EGG
  display-name: '{"text":"Shopkeeper","italic":false,"color":"green"}'
add-shop-creation-item-tag: true
identify-shop-creation-item-by-tag: true
prevent-shop-creation-item-regular-usage: true
invert-shop-type-and-object-type-selection: false
deleting-player-shop-returns-creation-item: false
create-player-shop-with-command: false
require-container-recently-placed: true
max-container-distance: 15
max-shops-per-player: -1
max-shops-perm-options: 5,15,25
protect-containers: true
prevent-item-movement: true
delete-shopkeeper-on-break-container: false
player-shopkeeper-inactive-days: 0
enabled-living-shops:
- VILLAGER
- ALLAY
- ARMADILLO
- AXOLOTL
- BEE
- BLAZE
- BOGGED
- BREEZE
- CAMEL
- CAT
- CAVE_SPIDER
- CHICKEN
- COD
- COW
- CREEPER
- DOLPHIN
- DONKEY
- DROWNED
- ENDERMAN
- EVOKER
- FOX
- FROG
- GHAST
- GIANT
- GLOW_SQUID
- GOAT
- HOGLIN
- HORSE
- HUSK
- ILLUSIONER
- IRON_GOLEM
- LLAMA
- MAGMA_CUBE
- MOOSHROOM
- MULE
- OCELOT
- PANDA
- PARROT
- PHANTOM
- PIG
- PIGLIN
- PIGLIN_BRUTE
- PILLAGER
- POLAR_BEAR
- PUFFERFISH
- RABBIT
- RAVAGER
- SALMON
- SHEEP
- SHULKER
- SILVERFISH
- SKELETON
- SKELETON_HORSE
- SLIME
- SNIFFER
- SNOW_GOLEM
- SPIDER
- SQUID
- STRAY
- STRIDER
- TADPOLE
- TRADER_LLAMA
- TROPICAL_FISH
- TURTLE
- VEX
- VINDICATOR
- WANDERING_TRADER
- WARDEN
- WITCH
- WITHER_SKELETON
- WOLF
- ZOGLIN
- ZOMBIE
- ZOMBIE_HORSE
- ZOMBIE_VILLAGER
- ZOMBIFIED_PIGLIN
disable-gravity: false
gravity-chunk-range: 4
mob-behavior-tick-period: 3
shulker-peek-if-player-nearby: true
shulker-peek-height: 0.3
silence-living-shop-entities: true
show-nameplates: true
always-show-nameplates: false
enable-citizen-shops: true
default-citizen-npc-type: PLAYER
set-citizen-npc-owner-of-player-shops: false
citizen-npc-fluid-pushable: false
cancel-citizen-npc-interactions: true
save-citizen-npcs-instantly: false
snapshots-save-citizen-npc-data: true
delete-invalid-citizen-shopkeepers: false
enable-sign-shops: true
enable-sign-post-shops: true
enable-hanging-sign-shops: true
name-regex: '[A-Za-z0-9 ]{3,25}'
naming-of-player-shops-via-item: false
allow-renaming-of-player-npc-shops: false
selling-empty-trade-result-item: GRAY_STAINED_GLASS_PANE
selling-empty-trade-item1: GRAY_STAINED_GLASS_PANE
selling-empty-trade-item2: GRAY_STAINED_GLASS_PANE
selling-empty-item1: BARRIER
selling-empty-item2: BARRIER
buying-empty-trade-result-item: GRAY_STAINED_GLASS_PANE
buying-empty-trade-item1: GRAY_STAINED_GLASS_PANE
buying-empty-trade-item2: AIR
buying-empty-result-item: BARRIER
buying-empty-item2: AIR
trading-empty-trade-result-item: GRAY_STAINED_GLASS_PANE
trading-empty-trade-item1: GRAY_STAINED_GLASS_PANE
trading-empty-trade-item2: GRAY_STAINED_GLASS_PANE
trading-empty-result-item: BARRIER
trading-empty-item1: BARRIER
trading-empty-item2: BARRIER
book-empty-trade-result-item: GRAY_STAINED_GLASS_PANE
book-empty-trade-item1: GRAY_STAINED_GLASS_PANE
book-empty-trade-item2: GRAY_STAINED_GLASS_PANE
book-empty-item1: BARRIER
book-empty-item2: BARRIER
max-trades-pages: 5
previous-page-item: WRITABLE_BOOK
next-page-item: WRITABLE_BOOK
current-page-item: WRITABLE_BOOK
trade-setup-item: PAPER
placeholder-item: PAPER
name-item: NAME_TAG
enable-all-equipment-editor-slots: false
enable-moving-of-player-shops: true
move-item: ENDER_PEARL
enable-container-option-on-player-shop: true
container-item: CHEST
trade-notifications-item: BELL
delete-item: BONE
disable-other-villagers: false
block-villager-spawns: false
disable-zombie-villager-curing: false
hire-other-villagers: false
disable-wandering-traders: false
block-wandering-trader-spawns: false
hire-wandering-traders: false
edit-regular-villagers: false
edit-regular-wandering-traders: false
hire-item: EMERALD
hire-other-villagers-costs: 1
hire-require-creation-permission: true
prevent-trading-with-own-shop: true
prevent-trading-while-owner-is-online: false
use-strict-item-comparison: false
increment-villager-statistics: false
simulate-villager-trading-sounds: true
simulate-villager-ambient-sounds: false
simulate-wandering-trader-trading-sounds: true
simulate-wandering-trader-ambient-sounds: false
simulate-trading-sounds-only-for-the-trading-player: true
trade-succeeded-sound:
  sound: minecraft:ui.button.click
  pitch: 2.0
  volume: 0.3
trade-failed-sound:
  sound: minecraft:block.barrel.close
  pitch: 2.0
  volume: 0.5
tax-rate: 0
tax-round-up: false
notify-players-about-trades: false
trade-notification-sound: ''
notify-shop-owners-about-trades: true
shop-owner-trade-notification-sound:
  sound: minecraft:entity.experience_orb.pickup
  volume: 0.25
trade-log-storage: DISABLED
trade-log-merge-duration-ticks: 300
trade-log-next-merge-timeout-ticks: 100
log-item-metadata: false
currency-item: EMERALD
high-currency-item: EMERALD_BLOCK
high-currency-value: 9
high-currency-min-cost: 20
