# -*- coding: utf-8 -*-
"""botgate 构建脚本（javac 全量 + 打 jar）。

用法：
    python botgate-src/build.py            # 编译全部 src -> 同目录
    python botgate-src/build.py --pack     # 编译 + 重打 botgate.jar
    python botgate-src/build.py --pack --deploy <mods_dir>   # 再拷到 mods 目录

classpath 复用 settlementsfix-src/javac-args-run.txt（同一套 MC/NeoForge 库）；
neoforge-server.jar 提到 mojang slim.jar 之前的逻辑与 settlementsfix 相同。
"""
import os
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import shutil
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
SIB = os.path.join(os.path.dirname(HERE), "settlementsfix-src")
JDK = os.environ.get("JDK21_BIN", r"C:\Program Files\Eclipse Adoptium\jdk-21.0.11.10-hotspot\bin")
JAVAC = os.path.join(JDK, "javac.exe" if os.name == "nt" else "javac")

FILES = [
    os.path.relpath(os.path.join(root, f), HERE).replace(os.sep, "/")
    for root, _dirs, files in os.walk(os.path.join(HERE, "dev"))
    for f in sorted(files)
    if f.endswith(".java")
]


def full_cp(libraries=None):
    if libraries:
        root = Path(libraries).resolve()
        neo = root / "net/neoforged/neoforge/21.1.248/neoforge-21.1.248-server.jar"
        srg = root / "net/minecraft/server/1.21.1-20240808.144430/server-1.21.1-20240808.144430-srg.jar"
        if not neo.is_file() or not srg.is_file():
            raise SystemExit("MC 1.21.1 / NeoForge 21.1.248 server libraries are required")
        # Use the installer's selected dependency versions, not every cached JAR
        # (the imported cache also contains obsolete Guava/ASM/NeoForge versions).
        args_file = neo.parent / "win_args.txt"
        legacy = next(line.split("=", 1)[1] for line in args_file.read_text(encoding="utf-8").splitlines()
                      if line.startswith("-DlegacyClassPath="))
        rest = [root.parent / p for p in legacy.split(";")]
        rest.append(neo.with_name("neoforge-21.1.248-universal.jar"))
        if any(not p.is_file() for p in rest):
            raise SystemExit("A library selected by NeoForge win_args.txt is missing")
        return os.pathsep.join(str(p) for p in (neo, srg, *rest))
    with open(os.path.join(SIB, "javac-args-run.txt"), encoding="utf-8") as f:
        cp_raw = f.readline().split('-cp "', 1)[1].split('"', 1)[0]
    sep = ";" if ";" in cp_raw else ":"
    parts = [p for p in cp_raw.split(sep) if os.path.exists(p)]
    neo = [p for p in parts if "neoforge-21.1.73-server.jar" in p]
    rest = [p for p in parts if "neoforge-21.1.73-server.jar" not in p]
    slim_idx = next((i for i, p in enumerate(rest) if p.endswith("-slim.jar")), None)
    if neo and slim_idx is not None:
        rest[slim_idx:slim_idx] = neo
    return sep.join(rest)


def compile_java(files, cp):
    # Compile into an empty directory: removed anonymous/nested classes must not
    # survive a rebuild and be repackaged from an older UI implementation.
    with tempfile.TemporaryDirectory(prefix=".javac-", dir=HERE) as output:
        cmd = [JAVAC, "-proc:none", "--release", "21", "-encoding", "UTF-8",
               "-cp", cp, "-d", output] + [os.path.join(HERE, f) for f in files]
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
        if r.returncode != 0:
            sys.stdout.write(r.stdout[:4000] + "\n")
            sys.stderr.write(r.stderr[:6000] + "\n")
            raise SystemExit("javac failed: %d" % r.returncode)
        classes_root = (Path(HERE) / "dev").resolve()
        # Only this source tree's generated bytecode is replaced, after success.
        previous = list(classes_root.rglob("*.class"))
        if any(not path.resolve().is_relative_to(classes_root) for path in previous):
            raise SystemExit("Refusing bytecode cleanup outside botgate source tree")
        for path in previous:
            path.unlink()
        for path in Path(output).rglob("*.class"):
            destination = Path(HERE) / path.relative_to(output)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, destination)
    print("compiled %d files" % len(files))


def pack(target=None):
    target = target or os.path.join(HERE, "botgate.jar")
    z = zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED)
    def add(path, name):
        info = zipfile.ZipInfo(name, (1980, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        z.writestr(info, Path(path).read_bytes())
    add(os.path.join(HERE, "botgate.mixins.json"), "botgate.mixins.json")
    add(os.path.join(HERE, "build-121", "neoforge.mods.toml"), "META-INF/neoforge.mods.toml")
    n = 0
    for root, dirs, files in os.walk(os.path.join(HERE, "dev")):
        dirs.sort()
        for f in sorted(files):
            if f.endswith(".class"):
                p = os.path.join(root, f)
                add(p, os.path.relpath(p, HERE).replace(os.sep, "/"))
                n += 1
    z.close()
    print("jar: %s (%d classes)" % (target, n))
    return target


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--libraries", default=str(Path(HERE).parents[1] / "server/mc/libraries"))
    parser.add_argument("--pack", action="store_true", help="Compatibility flag; builds always produce the JAR")
    parser.add_argument("--deploy", help="Optional explicit development mods directory")
    args = parser.parse_args()
    cp = full_cp(args.libraries)
    compile_java(FILES, cp)
    t = pack()
    with zipfile.ZipFile(t) as archive:
        if archive.testzip() is not None:
            raise SystemExit("Built archive failed CRC validation")
    def digest(path):
        return hashlib.sha256(Path(path).read_bytes()).hexdigest()
    inputs = FILES + ["botgate.mixins.json", "build-121/neoforge.mods.toml", "build.py"]
    record = {"minecraft": "1.21.1", "neoforge": "21.1.248", "java_release": 21,
              "jar": str(Path(t).resolve()), "sha256": digest(t),
              "sources": {f: digest(Path(HERE) / f) for f in sorted(inputs)},
              "classpath": {str(Path(p).relative_to(Path(args.libraries).resolve())): digest(p)
                            for p in cp.split(os.pathsep)}}
    Path(HERE, "build-record.json").write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print("sha256: " + record["sha256"])
    if args.deploy:
        mods = args.deploy
        import shutil
        shutil.copy2(t, os.path.join(mods, "botgate.jar"))
        print("deployed ->", mods)


if __name__ == "__main__":
    main()
