from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class WorldAdapter(Protocol):
    def snapshot(self) -> dict[str, Any]: ...

    def observe(self, radius: int = 8) -> dict[str, Any]: ...

    def open_lease(self, turn_id: str, expires_at: float, action_limit: int = 1) -> dict[str, Any]: ...

    def close_lease(self, blocking: bool = False) -> dict[str, Any]: ...

    def action(self, turn_id: str, tool: str, args: dict[str, Any]) -> dict[str, Any]: ...

    def action_status(self, body: dict[str, Any] | None = None) -> dict[str, Any]: ...

    def turn_receipts(self, turn_id: str) -> list[dict[str, Any]]: ...

    def inspect_block(self, x: int, y: int, z: int) -> dict[str, Any]: ...

    def inspect_container(self, x: int, y: int, z: int) -> dict[str, Any]: ...
